/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationipa;

import javax.swing.JOptionPane;

/**
 *
 * @author aychan
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TEXTAREA1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        jCheckBox38 = new javax.swing.JCheckBox();
        jCheckBox39 = new javax.swing.JCheckBox();
        jCheckBox40 = new javax.swing.JCheckBox();
        jCheckBox41 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        buttonRUN = new javax.swing.JButton();
        CLEARTEXT = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TEXTcontext1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jCheckBox42 = new javax.swing.JCheckBox();
        jCheckBox43 = new javax.swing.JCheckBox();
        jCheckBox44 = new javax.swing.JCheckBox();
        jCheckBox45 = new javax.swing.JCheckBox();
        jCheckBox46 = new javax.swing.JCheckBox();
        jCheckBox47 = new javax.swing.JCheckBox();
        jCheckBox48 = new javax.swing.JCheckBox();
        jCheckBox49 = new javax.swing.JCheckBox();
        jCheckBox50 = new javax.swing.JCheckBox();
        jCheckBox51 = new javax.swing.JCheckBox();
        jCheckBox52 = new javax.swing.JCheckBox();
        jCheckBox53 = new javax.swing.JCheckBox();
        jCheckBox54 = new javax.swing.JCheckBox();
        jCheckBox55 = new javax.swing.JCheckBox();
        jCheckBox56 = new javax.swing.JCheckBox();
        jCheckBox57 = new javax.swing.JCheckBox();
        jCheckBox58 = new javax.swing.JCheckBox();
        jCheckBox59 = new javax.swing.JCheckBox();
        jCheckBox60 = new javax.swing.JCheckBox();
        jCheckBox61 = new javax.swing.JCheckBox();
        jCheckBox62 = new javax.swing.JCheckBox();
        jCheckBox63 = new javax.swing.JCheckBox();
        jCheckBox64 = new javax.swing.JCheckBox();
        jCheckBox65 = new javax.swing.JCheckBox();
        jCheckBox66 = new javax.swing.JCheckBox();
        jCheckBox67 = new javax.swing.JCheckBox();
        jCheckBox68 = new javax.swing.JCheckBox();
        jCheckBox69 = new javax.swing.JCheckBox();
        jCheckBox70 = new javax.swing.JCheckBox();
        jCheckBox71 = new javax.swing.JCheckBox();
        jScrollPane7 = new javax.swing.JScrollPane();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jCheckBox72 = new javax.swing.JCheckBox();
        jCheckBox74 = new javax.swing.JCheckBox();
        jCheckBox75 = new javax.swing.JCheckBox();
        jCheckBox77 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Osaka", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IPA Compare Application ");

        TEXTAREA1.setColumns(20);
        TEXTAREA1.setRows(5);
        jScrollPane1.setViewportView(TEXTAREA1);

        jLabel2.setText("Insert Data");

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setText("Sound");
        jLayeredPane1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jCheckBox3.setText("Tap");
        jLayeredPane1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 296, -1, -1));

        jCheckBox2.setText("Syllabic");
        jLayeredPane1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 35, -1, -1));

        jCheckBox4.setText("Stress");
        jLayeredPane1.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 64, -1, -1));

        jCheckBox5.setText("Consonantal");
        jLayeredPane1.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 122, -1, -1));

        jCheckBox6.setText("Long");
        jLayeredPane1.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 93, -1, -1));

        jCheckBox7.setText("Sonorant");
        jLayeredPane1.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 151, -1, -1));

        jCheckBox8.setText("Approximant");
        jLayeredPane1.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 267, -1, -1));

        jCheckBox9.setText("Release");
        jLayeredPane1.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 238, -1, -1));

        jCheckBox10.setText("Delayed");
        jLayeredPane1.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 209, -1, -1));

        jCheckBox11.setText("Continuant");
        jLayeredPane1.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 180, -1, -1));

        jCheckBox23.setText("Trill");
        jLayeredPane1.add(jCheckBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 325, -1, -1));

        jCheckBox24.setText("Nasal");
        jLayeredPane1.add(jCheckBox24, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 354, -1, -1));

        jCheckBox25.setText("Voice");
        jLayeredPane1.add(jCheckBox25, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 383, -1, -1));

        jCheckBox26.setText("Spread GL");
        jLayeredPane1.add(jCheckBox26, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 412, -1, -1));

        jCheckBox27.setText("Constr GL");
        jLayeredPane1.add(jCheckBox27, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 441, -1, -1));

        jCheckBox28.setText("Labial");
        jLayeredPane1.add(jCheckBox28, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 470, -1, -1));

        jCheckBox29.setText("Round");
        jLayeredPane1.add(jCheckBox29, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 499, -1, -1));

        jCheckBox30.setText("Labiodental");
        jLayeredPane1.add(jCheckBox30, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 528, -1, -1));

        jCheckBox31.setText("Coronal");
        jLayeredPane1.add(jCheckBox31, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 557, -1, -1));

        jCheckBox32.setText("Anterior");
        jLayeredPane1.add(jCheckBox32, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 586, -1, -1));

        jCheckBox33.setText("Distributed");
        jLayeredPane1.add(jCheckBox33, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 615, -1, -1));

        jCheckBox34.setText("Strident");
        jLayeredPane1.add(jCheckBox34, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 644, -1, -1));

        jCheckBox35.setText("Lateral");
        jLayeredPane1.add(jCheckBox35, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 673, -1, -1));

        jCheckBox36.setText("Dorsal");
        jLayeredPane1.add(jCheckBox36, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 702, -1, -1));

        jCheckBox37.setText("High");
        jLayeredPane1.add(jCheckBox37, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 731, -1, -1));

        jCheckBox38.setText("Low");
        jLayeredPane1.add(jCheckBox38, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 760, -1, -1));

        jCheckBox39.setText("Front");
        jLayeredPane1.add(jCheckBox39, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 789, -1, -1));

        jCheckBox40.setText("Back");
        jLayeredPane1.add(jCheckBox40, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 818, -1, -1));

        jCheckBox41.setText("Tense");
        jLayeredPane1.add(jCheckBox41, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 847, -1, -1));

        jScrollPane2.setViewportView(jLayeredPane1);

        jLabel3.setText("Segments that all share");

        jLabel4.setText("Segments that all share");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Or, only the following natural class(es)");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        buttonRUN.setText("Run Program");
        buttonRUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRUNActionPerformed(evt);
            }
        });

        CLEARTEXT.setText("Clear Data");
        CLEARTEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARTEXTActionPerformed(evt);
            }
        });

        TEXTcontext1.setColumns(20);
        TEXTcontext1.setRows(5);
        jScrollPane4.setViewportView(TEXTcontext1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        jLabel6.setText("Contexts of first class");

        jLabel7.setText("Contexts of second class");

        jLayeredPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox42.setText("Sound");
        jLayeredPane3.add(jCheckBox42, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jCheckBox43.setText("Tap");
        jLayeredPane3.add(jCheckBox43, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 296, -1, -1));

        jCheckBox44.setText("Syllabic");
        jLayeredPane3.add(jCheckBox44, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 35, -1, -1));

        jCheckBox45.setText("Stress");
        jLayeredPane3.add(jCheckBox45, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 64, -1, -1));

        jCheckBox46.setText("Consonantal");
        jLayeredPane3.add(jCheckBox46, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 122, -1, -1));

        jCheckBox47.setText("Long");
        jLayeredPane3.add(jCheckBox47, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 93, -1, -1));

        jCheckBox48.setText("Sonorant");
        jLayeredPane3.add(jCheckBox48, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 151, -1, -1));

        jCheckBox49.setText("Approximant");
        jLayeredPane3.add(jCheckBox49, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 267, -1, -1));

        jCheckBox50.setText("Release");
        jLayeredPane3.add(jCheckBox50, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 238, -1, -1));

        jCheckBox51.setText("Delayed");
        jLayeredPane3.add(jCheckBox51, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 209, -1, -1));

        jCheckBox52.setText("Continuant");
        jLayeredPane3.add(jCheckBox52, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 180, -1, -1));

        jCheckBox53.setText("Trill");
        jLayeredPane3.add(jCheckBox53, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 325, -1, -1));

        jCheckBox54.setText("Nasal");
        jLayeredPane3.add(jCheckBox54, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 354, -1, -1));

        jCheckBox55.setText("Voice");
        jLayeredPane3.add(jCheckBox55, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 383, -1, -1));

        jCheckBox56.setText("Spread GL");
        jLayeredPane3.add(jCheckBox56, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 412, -1, -1));

        jCheckBox57.setText("Constr GL");
        jLayeredPane3.add(jCheckBox57, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 441, -1, -1));

        jCheckBox58.setText("Labial");
        jLayeredPane3.add(jCheckBox58, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 470, -1, -1));

        jCheckBox59.setText("Round");
        jLayeredPane3.add(jCheckBox59, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 499, -1, -1));

        jCheckBox60.setText("Labiodental");
        jLayeredPane3.add(jCheckBox60, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 528, -1, -1));

        jCheckBox61.setText("Coronal");
        jLayeredPane3.add(jCheckBox61, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 557, -1, -1));

        jCheckBox62.setText("Anterior");
        jLayeredPane3.add(jCheckBox62, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 586, -1, -1));

        jCheckBox63.setText("Distributed");
        jLayeredPane3.add(jCheckBox63, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 615, -1, -1));

        jCheckBox64.setText("Strident");
        jLayeredPane3.add(jCheckBox64, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 644, -1, -1));

        jCheckBox65.setText("Lateral");
        jLayeredPane3.add(jCheckBox65, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 673, -1, -1));

        jCheckBox66.setText("Dorsal");
        jLayeredPane3.add(jCheckBox66, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 702, -1, -1));

        jCheckBox67.setText("High");
        jLayeredPane3.add(jCheckBox67, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 731, -1, -1));

        jCheckBox68.setText("Low");
        jLayeredPane3.add(jCheckBox68, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 760, -1, -1));

        jCheckBox69.setText("Front");
        jLayeredPane3.add(jCheckBox69, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 789, -1, -1));

        jCheckBox70.setText("Back");
        jLayeredPane3.add(jCheckBox70, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 818, -1, -1));

        jCheckBox71.setText("Tense");
        jLayeredPane3.add(jCheckBox71, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 847, -1, -1));

        jScrollPane6.setViewportView(jLayeredPane3);

        jLayeredPane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox72.setText("Segments before first class");
        jLayeredPane4.add(jCheckBox72, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jCheckBox74.setText("Segments after first class");
        jLayeredPane4.add(jCheckBox74, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 35, -1, -1));

        jCheckBox75.setText("Segments before second class");
        jLayeredPane4.add(jCheckBox75, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 64, -1, -1));

        jCheckBox77.setText("Segments after second class");
        jLayeredPane4.add(jCheckBox77, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 93, -1, -1));

        jScrollPane7.setViewportView(jLayeredPane4);

        jLabel8.setText("Show all features in common between: ");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jLabel9.setText("All Share:");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane8.setViewportView(jTextArea3);

        jLabel10.setText("Contexts which both classes appear:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CLEARTEXT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRUN)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(100, 100, 100))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(194, 194, 194)
                                .addComponent(jLabel3)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(85, 85, 85)
                                    .addComponent(jLabel9))
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(0, 430, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8))))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CLEARTEXT)
                                .addComponent(buttonRUN))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void CLEARTEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARTEXTActionPerformed
        // CLEARS TEXT FROM LARGE TEXT AREA INPUT
        
            if (JOptionPane.showConfirmDialog(null, "Clear Data?", "", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                TEXTAREA1.setText(""); //CLEAR TEXT FIELD        // yes option
            } else {
                // no option
            }
        
        
    }//GEN-LAST:event_CLEARTEXTActionPerformed

    private void buttonRUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRUNActionPerformed
        /*
        Very Important method:
        on Click: will use Severin's code to parse data, and place into TEXTcontext1 and TEXTcontext2
        for now: this method take data from TEXTAREA1 and places it into TEXTcontext2
        */
        
        
        if(TEXTAREA1.getText() != null){ 
            String data = TEXTAREA1.getText();
            TEXTcontext1.setText(data);
        }
    }//GEN-LAST:event_buttonRUNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLEARTEXT;
    private javax.swing.JTextArea TEXTAREA1;
    private javax.swing.JTextArea TEXTcontext1;
    private javax.swing.JButton buttonRUN;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox37;
    private javax.swing.JCheckBox jCheckBox38;
    private javax.swing.JCheckBox jCheckBox39;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox40;
    private javax.swing.JCheckBox jCheckBox41;
    private javax.swing.JCheckBox jCheckBox42;
    private javax.swing.JCheckBox jCheckBox43;
    private javax.swing.JCheckBox jCheckBox44;
    private javax.swing.JCheckBox jCheckBox45;
    private javax.swing.JCheckBox jCheckBox46;
    private javax.swing.JCheckBox jCheckBox47;
    private javax.swing.JCheckBox jCheckBox48;
    private javax.swing.JCheckBox jCheckBox49;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox50;
    private javax.swing.JCheckBox jCheckBox51;
    private javax.swing.JCheckBox jCheckBox52;
    private javax.swing.JCheckBox jCheckBox53;
    private javax.swing.JCheckBox jCheckBox54;
    private javax.swing.JCheckBox jCheckBox55;
    private javax.swing.JCheckBox jCheckBox56;
    private javax.swing.JCheckBox jCheckBox57;
    private javax.swing.JCheckBox jCheckBox58;
    private javax.swing.JCheckBox jCheckBox59;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox60;
    private javax.swing.JCheckBox jCheckBox61;
    private javax.swing.JCheckBox jCheckBox62;
    private javax.swing.JCheckBox jCheckBox63;
    private javax.swing.JCheckBox jCheckBox64;
    private javax.swing.JCheckBox jCheckBox65;
    private javax.swing.JCheckBox jCheckBox66;
    private javax.swing.JCheckBox jCheckBox67;
    private javax.swing.JCheckBox jCheckBox68;
    private javax.swing.JCheckBox jCheckBox69;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox70;
    private javax.swing.JCheckBox jCheckBox71;
    private javax.swing.JCheckBox jCheckBox72;
    private javax.swing.JCheckBox jCheckBox74;
    private javax.swing.JCheckBox jCheckBox75;
    private javax.swing.JCheckBox jCheckBox77;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
